config/routes.rb
Rails.application.routes.draw do
  root 'photos#index'
  resources :photos do
    member do
      put "like" =>"photos#like"
    end
  end
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  has_attached_file :file, styles: { medium: "1000x1000>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :file, content_type: /\Aimage\/.*\z/
  validates :camera, length: { maximum: 200 }
  validates :film, length: { maximum: 200 }
  validates :file, presence: true
  acts_as_votable

end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  acts_as_voter
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def new
    @photo = Photo.new
  end

  def index
    @photos = Photo.page(params[:page]).per(5)
  end

  def show
    @photo = Photo.find(params[:id])
  end

  def create
   @photo = Photo.new(permit_photo)
   @photo.user_id = current_user.id
   if @photo.save
     redirect_to action: :index
   else
     redirect_to new_photo_path
   end
 end

 def destroy
   @photo = Photo.find(params[:id])
   @photo.destroy
   redirect_to action: :index
 end

 def like
   @photo = Photo.find(params[:id])
   @photo.upvote_from current_user
   render layout: false
 end

  private

  def permit_photo
    params.require(:photo).permit(:file,:camera,:film)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title #35mm
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    %nav.navbar.navbar-expand-lg.navbar-dark.bg-dark.static-top
      .container
        = link_to "#35mm", root_url, class: "navbar-brand"
        %button.navbar-toggler{"aria-controls" => "navbarResponsive", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarResponsive", "data-toggle" => "collapse", type: "button"}
          %span.navbar-toggler-icon
        #navbarResponsive.collapse.navbar-collapse
          %ul.nav.navbar-nav
            - if current_user
              %li
                = link_to "Add Photo", new_photo_path
        %ul.nav.navbar-nav.navbar-right
          - if current_user
            %li
              = link_to "Logout", destroy_user_session_path, method: :delete
          - else
            %li
              = link_to "Login", new_user_session_path
            %li
              = link_to "Register", new_user_registration_path
    .container
      .row
        .col-lg-12.text-center
          %br/
          = yield

app/views/photos/index.html.haml
- @photos.each do |f|
  .white
    = image_tag f.file.url(:medium)
    = f.camera
    = f.film
    - if current_user
      - if current_user.id == f.user_id || current_user.admin == true
        = button_to "Delete", photo_path(f),  :class=>"inbox-sf-add-btn tip", method: :delete
  = link_to like_photo_path(f.id), method: :put, remote: :true, class: 'like-post' do
    .like-button
      = image_tag('like2.png', alt: 'like me')
      %div{:id => "like-count_#{f.id}"}
        = f.get_upvotes.size
.pag
  = paginate @photos

app/views/photos/like.js.haml
:plain
  $('#like-count_#{@photo.id}').html("#{@photo.get_upvotes.size}");

app/views/photos/new.html.haml
%h1 New Photo
= form_for @photo, html: { multipart: true } do |f|
  = f.label :camera
  .list= f.text_area :camera
  = f.label :film
  .list= f.text_area :film
  = f.label :file
  .list= f.file_field :file
  .list= f.submit

app/views/photos/show.html.haml
= image_tag(@photo.file.url(:medium))
= @photo.camera
= @photo.film